export const PHOTO_CATEGORY_OPTIONS = [
    { value: 1, label: 'Food and Drink' },
    { value: 2, label: 'Wallpapers' },
    { value: 3, label: 'Nature' },
    { value: 4, label: 'Love' },
    { value: 5, label: 'People' },
    { value: 6, label: 'Animals' },
    { value: 7, label: 'Architecture - Kiến trúc' },
    { value: 8, label: 'Interiors - Nội thất' },
    { value: 9, label: 'Fashion' },
    { value: 10, label: 'Street Photography' },
    { value: 11, label: 'Textures & Patterns' },
    { value: 12, label: 'Technology' },
    { value: 13, label: 'Travel' },
    { value: 14, label: 'Sport' },
    { value: 15, label: 'Spirituality - Tâm linh' },
    { value: 16, label: 'Arts & Culture' },
    { value: 17, label: 'Film' },
    { value: 18, label: 'Vihicle' },
    { value: 19, label: 'Others' },
]
